import { Arquivo } from './arquivo';

export const ARQUIVOS: Arquivo[] = [
{
    id: 1,
    sequencialDoArquivo: '000001',
    tipoSolicitacaoDeRegistro: 10,
    dataDeEmissaoDoMovimento: '01/07/2019',
    dataInicioDeVigencia: '02/09/2019',
    dataTerminoDeVigencia: '11/10/2020',
    numeroDeApolice: 1234567890,
    numeroDoEndosso: 9127126,
    numeroDoEndossoAssociado: 23214124,
    numeroDoRegistroDoProdutoSUSEP: 1234567890,
    grupoDoSeguro: 7,
    grupoDoSeguroDescricao: "Riscos Financeiros",
    ramoDoSeguro: 75,
    ramoDoSeguroDescricao: 'Garantia Segurado - Setor Público',
    codigoDaCobertura: 13,
    nome: {
        razaoSocialSegurado: 'Lucas dos Santos Caetano',
        razaoSocialTomador: 'CERC'
    },
    cpf: {
        cnpjSegurado: '397.474.177-19',
        cnpjTomador: '123.324/0001-91',
    },
    tipoEntidadeSegurado: 1,
    limiteMaximoDeGarantiaLMG: 100000,
    codigoDeMoeda: 790,
    cotacaoMoeda: 1,
    premioEmitidoBRL: 1000,
    premioEmitidoMoeda: 1000,
    custoDeAquisicao: 0,
    custoDeEmissaoDaApolice: 0,
    impostoSobreOperacoesFinanceirasIOF: 0,
    fracionamento: 1,
    situacao: 1,
    contratoDoObjetoSegurado: 'Contrato',
    tipoEntidadeTomador: 1,
    totalTomadoresDoGrupoEconomico: 1,
    tipoCosseguro: 1,
    codigoSusepCosegurador: 12345,
    percentualDeCoseguro: 20,
    importanciaSeguradaCosseguro: 20000,
    premioCosseguro: 200,
    totalCosseguradores: 0,
    tipoResseguro: 1,
    contratoDeResseguro: 9876543,
    totalContratosDeResseguro: 2,
    codigoSusepRessegurador: 12345,
    totalResseguradores: 3,
    percentualdeResseguro: 30,
    importanciaSeguradaResseguro: 6000,
    premioResseguro: 60,
    codigoSusepBroker: 5432,
    totalBroker: 2,
},
{
    id: 1,
    sequencialDoArquivo: '000001',
    tipoSolicitacaoDeRegistro: 10,
    dataDeEmissaoDoMovimento: '01/07/2019',
    dataInicioDeVigencia: '02/09/2019',
    dataTerminoDeVigencia: '11/10/2020',
    numeroDeApolice: 1234567890,
    numeroDoEndosso: 9127126,
    numeroDoEndossoAssociado: 23214124,
    numeroDoRegistroDoProdutoSUSEP: 1234567890,
    grupoDoSeguro: 7,
    grupoDoSeguroDescricao: "Riscos Financeiros",
    ramoDoSeguro: 75,
    ramoDoSeguroDescricao: 'Garantia Segurado - Setor Público',
    codigoDaCobertura: 13,
    nome: {
        razaoSocialSegurado: 'Lucas dos Santos Caetano',
        razaoSocialTomador: 'CERC'
    },
    cpf: {
        cnpjSegurado: '397.474.177-19',
        cnpjTomador: '123.324/0001-91',
    },
    tipoEntidadeSegurado: 1,
    limiteMaximoDeGarantiaLMG: 100000,
    codigoDeMoeda: 790,
    cotacaoMoeda: 1,
    premioEmitidoBRL: 1000,
    premioEmitidoMoeda: 1000,
    custoDeAquisicao: 0,
    custoDeEmissaoDaApolice: 0,
    impostoSobreOperacoesFinanceirasIOF: 0,
    fracionamento: 1,
    situacao: 1,
    contratoDoObjetoSegurado: 'Contrato',
    tipoEntidadeTomador: 1,
    totalTomadoresDoGrupoEconomico: 1,
    tipoCosseguro: 1,
    codigoSusepCosegurador: 12345,
    percentualDeCoseguro: 20,
    importanciaSeguradaCosseguro: 20000,
    premioCosseguro: 200,
    totalCosseguradores: 2,
    tipoResseguro: 1,
    contratoDeResseguro: 9876543,
    totalContratosDeResseguro: 2,
    codigoSusepRessegurador: 12345,
    totalResseguradores: 3,
    percentualdeResseguro: 30,
    importanciaSeguradaResseguro: 6000,
    premioResseguro: 60,
    codigoSusepBroker: 5432,
    totalBroker: 2,
},
{
    id: 1,
    sequencialDoArquivo: '000001',
    tipoSolicitacaoDeRegistro: 10,
    dataDeEmissaoDoMovimento: '01/07/2019',
    dataInicioDeVigencia: '02/09/2019',
    dataTerminoDeVigencia: '11/10/2020',
    numeroDeApolice: 1234567890,
    numeroDoEndosso: 9127126,
    numeroDoEndossoAssociado: 23214124,
    numeroDoRegistroDoProdutoSUSEP: 1234567890,
    grupoDoSeguro: 7,
    grupoDoSeguroDescricao: "Riscos Financeiros",
    ramoDoSeguro: 75,
    ramoDoSeguroDescricao: 'Garantia Segurado - Setor Público',
    codigoDaCobertura: 13,
    nome: {
        razaoSocialSegurado: 'Lucas dos Santos Caetano',
        razaoSocialTomador: 'CERC'
    },
    cpf: {
        cnpjSegurado: '397.474.177-19',
        cnpjTomador: '123.324/0001-91',
    },
    tipoEntidadeSegurado: 1,
    limiteMaximoDeGarantiaLMG: 100000,
    codigoDeMoeda: 790,
    cotacaoMoeda: 1,
    premioEmitidoBRL: 1000,
    premioEmitidoMoeda: 1000,
    custoDeAquisicao: 0,
    custoDeEmissaoDaApolice: 0,
    impostoSobreOperacoesFinanceirasIOF: 0,
    fracionamento: 1,
    situacao: 1,
    contratoDoObjetoSegurado: 'Contrato',
    tipoEntidadeTomador: 1,
    totalTomadoresDoGrupoEconomico: 1,
    tipoCosseguro: 1,
    codigoSusepCosegurador: 12345,
    percentualDeCoseguro: 20,
    importanciaSeguradaCosseguro: 20000,
    premioCosseguro: 200,
    totalCosseguradores: 2,
    tipoResseguro: 1,
    contratoDeResseguro: 9876543,
    totalContratosDeResseguro: 2,
    codigoSusepRessegurador: 12345,
    totalResseguradores: 3,
    percentualdeResseguro: 30,
    importanciaSeguradaResseguro: 6000,
    premioResseguro: 60,
    codigoSusepBroker: 5432,
    totalBroker: 2,
},
{
    id: 1,
    sequencialDoArquivo: '000001',
    tipoSolicitacaoDeRegistro: 10,
    dataDeEmissaoDoMovimento: '01/07/2019',
    dataInicioDeVigencia: '02/09/2019',
    dataTerminoDeVigencia: '11/10/2020',
    numeroDeApolice: 1234567890,
    numeroDoEndosso: 9127126,
    numeroDoEndossoAssociado: 23214124,
    numeroDoRegistroDoProdutoSUSEP: 1234567890,
    grupoDoSeguro: 7,
    grupoDoSeguroDescricao: "Riscos Financeiros",
    ramoDoSeguro: 75,
    ramoDoSeguroDescricao: 'Garantia Segurado - Setor Público',
    codigoDaCobertura: 13,
    nome: {
        razaoSocialSegurado: 'Lucas dos Santos Caetano',
        razaoSocialTomador: 'CERC'
    },
    cpf: {
        cnpjSegurado: '397.474.177-19',
        cnpjTomador: '123.324/0001-91',
    },
    tipoEntidadeSegurado: 1,
    limiteMaximoDeGarantiaLMG: 100000,
    codigoDeMoeda: 790,
    cotacaoMoeda: 1,
    premioEmitidoBRL: 1000,
    premioEmitidoMoeda: 1000,
    custoDeAquisicao: 0,
    custoDeEmissaoDaApolice: 0,
    impostoSobreOperacoesFinanceirasIOF: 0,
    fracionamento: 1,
    situacao: 1,
    contratoDoObjetoSegurado: 'Contrato',
    tipoEntidadeTomador: 1,
    totalTomadoresDoGrupoEconomico: 1,
    tipoCosseguro: 1,
    codigoSusepCosegurador: 12345,
    percentualDeCoseguro: 20,
    importanciaSeguradaCosseguro: 20000,
    premioCosseguro: 200,
    totalCosseguradores: 2,
    tipoResseguro: 1,
    contratoDeResseguro: 9876543,
    totalContratosDeResseguro: 2,
    codigoSusepRessegurador: 12345,
    totalResseguradores: 3,
    percentualdeResseguro: 30,
    importanciaSeguradaResseguro: 6000,
    premioResseguro: 60,
    codigoSusepBroker: 5432,
    totalBroker: 2,
},
{
    id: 1,
    sequencialDoArquivo: '000001',
    tipoSolicitacaoDeRegistro: 10,
    dataDeEmissaoDoMovimento: '01/07/2019',
    dataInicioDeVigencia: '02/09/2019',
    dataTerminoDeVigencia: '11/10/2020',
    numeroDeApolice: 1234567890,
    numeroDoEndosso: 9127126,
    numeroDoEndossoAssociado: 23214124,
    numeroDoRegistroDoProdutoSUSEP: 1234567890,
    grupoDoSeguro: 7,
    grupoDoSeguroDescricao: "Riscos Financeiros",
    ramoDoSeguro: 75,
    ramoDoSeguroDescricao: 'Garantia Segurado - Setor Público',
    codigoDaCobertura: 13,
    nome: {
        razaoSocialSegurado: 'Lucas dos Santos Caetano',
        razaoSocialTomador: 'CERC'
    },
    cpf: {
        cnpjSegurado: '397.474.177-19',
        cnpjTomador: '123.324/0001-91',
    },
    tipoEntidadeSegurado: 1,
    limiteMaximoDeGarantiaLMG: 100000,
    codigoDeMoeda: 790,
    cotacaoMoeda: 1,
    premioEmitidoBRL: 1000,
    premioEmitidoMoeda: 1000,
    custoDeAquisicao: 0,
    custoDeEmissaoDaApolice: 0,
    impostoSobreOperacoesFinanceirasIOF: 0,
    fracionamento: 1,
    situacao: 1,
    contratoDoObjetoSegurado: 'Contrato',
    tipoEntidadeTomador: 1,
    totalTomadoresDoGrupoEconomico: 1,
    tipoCosseguro: 1,
    codigoSusepCosegurador: 12345,
    percentualDeCoseguro: 20,
    importanciaSeguradaCosseguro: 20000,
    premioCosseguro: 200,
    totalCosseguradores: 2,
    tipoResseguro: 1,
    contratoDeResseguro: 9876543,
    totalContratosDeResseguro: 2,
    codigoSusepRessegurador: 12345,
    totalResseguradores: 3,
    percentualdeResseguro: 30,
    importanciaSeguradaResseguro: 6000,
    premioResseguro: 60,
    codigoSusepBroker: 5432,
    totalBroker: 2,
}
]